apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "6TbglRrdG/AoDsk1XS+99OSHqblc2KC/zWXqFJqwXlNwZwwjPjGVPUQNIC3LiAON\nvXgRSZ2BBszhpDM9vYvLUUJ6Mm3LD76D+cP9jEhAS9FyJ8fzopSBNii51x6HEZ/R\nOwQi2qQ7sthMtC3PdrPiirPM4FRKIhOA+4UxbF2eyjM="
