apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "r852t0diH+lMVhFPuRM8XKrwSkU16ukmhoyuiFZhCgQMFExIFLRWzhmjWBVnv2tC\no+foKShhm+VxDLaPMp1Q5bS77xfQ9BvI+YBsD56JmyD2YuYTe/cm31a0fmXm4ph4\nGW0NOE74x3CPlR84/LglJVONOXXBHjBq3R9OVUops78="
